### ISSUE TITLE
Readme code does not work

### ISSUE THREAD

**Issue by aquaresima** [JuliaGeometry/VoronoiCells.jl#17]
Hi, 
I just tried the code that you offer in the Readme and it does not work:
Julia Version 1.5.2
VoronoiCells v0.1.5
GeometryBasics v0.3.11

```
using VoronoiCells
using GeometryBasics
using Plots
using Random

Random.seed!(1337)
rect = Rectangle(Point2(0, 0), Point2(1, 1))
points = [Point2(rand(), rand()) for _ in 1:10]
tess = voronoicells(points, rect);

```

`Rectangle` should be `Rect2D` 
and `voronoicells` is defined over `PointGenerators`, no idea what's that.

Can you offer a minimal working example, I ll work from there.

**Comment by robertdj** [comment]
Hi

Thanks for reaching out. The latest version of VoronoiCells is 0.2.1. With that version the code works  on my computer. 
Try updating and run the code again.

**Comment by robertdj** [comment]
@aquaresima Any luck with an updated VoronoiCells?

**Comment by aquaresima** [comment]
Hi! Yes, sorry for not having responded to you!
The code worked smoothly after the update. I had an old version of StatPlots that was blocking all the chain of updates!
I produced this fancy gif about how Australian vowels map to British pronunciation

![anim_vowels](https://user-images.githubusercontent.com/53222249/111639016-28717f80-87fb-11eb-9a50-eb81563019b2.gif)

**Comment by aquaresima** [comment]
Perhaps, I can ask you for some further help on this.
I would like the container rectangle to be a trapezoid, like this:
![image](https://user-images.githubusercontent.com/53222249/111639326-71c1cf00-87fb-11eb-9a3c-f5ad3fc42178.png)

Do you think this would be possible? I couldn't find an easy way out with  the actual code!

**Comment by robertdj** [comment]
Glad it worked :-) And very cool animation!

I think it should be possible for the bounding window to be any convex polygon. But I haven't spelled out the details, so no promises :-) 
It would certainly require code changes. Let me think about it.
