### ISSUE TITLE
Outer rect/corner problem

### ISSUE THREAD

**Issue by philbit** [JuliaGeometry/VoronoiCells.jl#21]
First, thanks for the great work!

Sometimes, edges that go to the outer observation rectangle do not properly line up between neighboring Voronoi cells, like in this MWE:

```julia
using VoronoiCells
using GeometryBasics
using Plots
xcoord = [15.88214474527994
    18.863039659292394
    30.328176045427
    28.037431454174133
    40.31988094097913
    30.665194659310004
    44.11595650945559
    43.56366650514183]
ycoord = [24.68379930190996
    13.965766368581402
    18.398517333119784
    7.753520072641838
    26.694764409793734
    21.4580117453147
    25.27856333715974
    14.285077941536494]

rect = Rectangle(Point2(0, 0), Point2(50, 40))
points = [Point2(x, y) for (x,y) in zip(xcoord,ycoord)]
tess = voronoicells(points, rect);
Plots.scatter(points, markersize = 6, label = "center points")
plot!(tess, legend = :bottomleft, aspect_ratio=:equal)
```

This leads to the following tesselation:

![result](https://user-images.githubusercontent.com/8332598/130234205-afa0b3cb-f24a-4da6-bacc-2ea28778f1d4.png)

As you can see, there are two vertices near the top-right corner that should be identical but aren't. Any idea what is going on here? Could it have anything to do with the conservative estimates for the transformation to the [1,2]x[1,2] rectangle for `VoronoiDelaunay`?

**Comment by philbit** [comment]
Actually, I think there is a deeper problem here, but not sure if it's a separate one or connected to this: Visually, some edges of the voronoi cells don't seem quite perpendicular to the line connecting the generators of the adjacent cells. You can see it clearly here, where I've reduced the height of the outer rectangle even further (from 40 to 30):

![result](https://user-images.githubusercontent.com/8332598/130234491-f77e12cf-b3fe-47f4-8433-c29fe058af80.png)

So I think there might be a general problem with non-square observation regions. Perhaps they are scaled differently when transformed for the `VoronoiDelaunay` package. As I said, I am not sure if this also causes the actual issue above. If it is not, I can open another issue just for this.

**Comment by robertdj** [comment]
Thanks for posting this. It's good to find these troublesome edge cases. I'll probably have time to look into this during the weekend.

**Comment by robertdj** [comment]
I'm afraid I need to look more thoroughly into this. I'll try to get around to it by the end of next week.

**Comment by philbit** [comment]
This should fix the non-square geometry problem. I think this might have also been the issue with the wrong corner behavior above, as the metric was distorted by the unequal scaling in both directions. This might have led to the wrong nearest neighbor detected for the corner (but I didn't test this thoroughly, I just couldn't find an example where it breaks so far with the new version).

Above plots updated:

50x40
![result](https://user-images.githubusercontent.com/8332598/130643732-cce4984c-da50-420d-8d2b-86246f97e47b.png)



50x30
![result](https://user-images.githubusercontent.com/8332598/130643854-5f6b58dd-7724-4ddd-9110-fce259657e29.png)


I'll come back to this if I find another problematic example, but for now I consider this case closed with the pull request.

**Comment by philbit** [comment]
Just for completeness, I reduced the width of the domain from `50 x 40` to `47.6 x 40.`, so the Voronoi cell edge between the two points on the upper right meets the outer rectangle near the corner (which is where the problem occurred before). Now it is correct. Of course that doesn't prove anything, but I think it's now even more likely than before that the original issue is fixed.

![result](https://user-images.githubusercontent.com/8332598/130645733-047e14c5-e163-4eb9-8a63-86e8b22ee15b.png)
