### ISSUE TITLE
Manifest.toml in repo

### ISSUE THREAD

**Issue by philbit** [JuliaGeometry/VoronoiCells.jl#23]
`Manifest.toml` is part of the the repo.

**Comment by robertdj** [comment]
I'm not sure if `Manifest.toml` should be included or not? A quick look at some large projects (e.g. `DifferentialEquations` and `Flux`) show that some include it and others do not. 
Do you have a reference for an official recommendation?

**Comment by philbit** [comment]
Ah, sorry, I didn't think about it deeply when I added this. Apparently I happened to look at packages that didn't include it when I was looking for examples, so I didn't question my general rule not to include it for packages. The reason I created the pull request was that I encountered an issue due to the existing `Manifest.toml`, some version incompatability that resulted in not being able to compile all the dependencies on my system. So I had to update the dependencies anyway, changing the `Manifest.toml` (somehow reinforcing my belief that it shouldn't be there in the first place).

According to [this](https://discourse.julialang.org/t/does-manifest-toml-belong-in-the-repository/12029/14) discussion, there seems to be a tendency not to include it for packages. That's also what I do. At the end of the thread, the julia version specificity (and perhaps in some cases also system specificity!?) is mentioned which is the main reason for me not to include it.

But having researched this a bit more now it doesn't seem to be as clear cut as I thought. It's also not a major issue. So feel free to close the issue and pull request if you don't like it.

**Comment by robertdj** [comment]
Thanks for the link to that discussion. I actually ran into trouble when trying to test this package with both Julia 1.5 and 1.6. I didn't realize that it was due to the manifest file!
Would you mind adding version 1.6 to `.github/workflows/ci.yml` in your PR to see if that works with your change? (I don't think I can change anything in your PR.)

**Comment by philbit** [comment]
I just invited you to my fork as a collaborator. Then you can play around with the CI workflow yourself, hopefully avoiding the back and forth (I cannot start the workflow, for example). Let me know if there are any problems.

By the way, this is part of what gitignore.io generates for julia:

```
# File generated by Pkg, the package manager, based on a corresponding Project.toml
# It records a fixed state of all packages used by the project. As such, it should not be
# committed for packages, but should be committed for applications that require a static
# environment.
Manifest.toml
```

Since I use it a lot, it was kind of automatic for me so far not to include it in the repo.
