### ISSUE TITLE
Plotting Voronoi cells filled-in by area

### ISSUE THREAD

**Issue by jacobusmmsmit** [JuliaGeometry/VoronoiCells.jl#27]
In some applications, such as mine, it is useful to be able to fill in the Voronoi cells when plotted and have the colour correspond to the area of the cell. This is simple enough to do using the code from the example:

```
using VoronoiCells
using GeometryBasics
using Plots
using Random

Random.seed!(42)
rect = Rectangle(Point2(0, 0), Point2(1, 1))
points = [Point2(rand(), rand()) for _ = 1:10]
tess = voronoicells(points, rect);

function cell_to_shape(cell)
    xs = first.(cell)
    ys = last.(cell)
    return Shape(xs, ys)
end


begin
    vareas = voronoiarea(tess)
    voronoi_cells_plot = plot(aspect_ratio = 1.0, lims = (0, 1), clims = (0, maximum(vareas)))
    for (i, cell) in enumerate(tess.Cells)
        plot!(cell_to_shape(cell), fill_z = vareas[i], label = "", alpha = 1)
    end
    scatter!(points, markersize = 6, label = "Generators", mc = :white)
    plot!(tess, legend = :topleft, lc = :black)
    voronoi_cells_plot
end
```
and this produces the following plot:
![filled_cells_example](https://user-images.githubusercontent.com/57063134/146820767-ade27bf6-fc37-4b04-9e51-0e3f338a9036.png)

That said, this is quite hacky as it isn't done just using `RecipesBase`. Do you think you have time to implement this in `RecipesBase`?

**Comment by robertdj** [comment]
It looks nice :-) But I don't understand the problem with making your own method that creates this plot?
