### ISSUE TITLE
Is it possible to extend to higher dimensions?

### ISSUE THREAD

**Issue by maphdze** [JuliaGeometry/VoronoiCells.jl#29]
I found that `VoronoiCells` is fastest package to generate bounded Voronoi partition of a space, compared with `MPT` toolbox in matlab and 'voronoin' in matlab which called `QHull`. Is it possible to extend this package to higher dimensions? And what is the difficulty?

**Comment by robertdj** [comment]
Good to hear that it is useful to you! 

AFAIK this is not possible: VoronoiCells use the [VoronoiDelaunay package](https://github.com/JuliaGeometry/VoronoiDelaunay.jl) to compute the internal lines of the Voronoi tessellation, whereas the boundaries are handled by VoronoiCells. 
From VoronoiDelaunay's README you see that it only works for 2D.

**Comment by maphdze** [comment]
> Good to hear that it is useful to you!
> 
> AFAIK this is not possible: VoronoiCells use the [VoronoiDelaunay package](https://github.com/JuliaGeometry/VoronoiDelaunay.jl) to compute the internal lines of the Voronoi tessellation, whereas the boundaries are handled by VoronoiCells. From VoronoiDelaunay's README you see that it only works for 2D.

Thank you for reply! I see it. Maybe we should call `QHull` in julia like `MiniQHull` for higher dimension.
