### ISSUE TITLE
ERROR: Unsatisfiable requirements detected for package VoronoiCells [e3e34ffb]

### ISSUE THREAD

**Issue by chris-revell** [JuliaGeometry/VoronoiCells.jl#7]
Cannot seem to install this package. Error is as follows:

ERROR: Unsatisfiable requirements detected for package VoronoiCells [e3e34ffb]:
 VoronoiCells [e3e34ffb] log:
 ├─possible versions are: [0.0.1-0.0.2, 0.1.0-0.1.4] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.2, 0.1.0-0.1.4]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

**Comment by robertdj** [comment]
I have forgotten to register it -- thanks for notifying me. I'll try to get around to this soon (I have forgotten how to). 

If you want to try out the package then clone the repo and make a new project in the repo's folder.

**Comment by robertdj** [comment]
I have made a PR for registering VoronoiCells: https://github.com/JuliaRegistries/General/pull/2612

When it goes through you should be able to install the package. If it doesn't work then reopen this issue.

**Comment by chris-revell** [comment]
That's great, thanks.
